from __future__ import annotations

import re
import unittest
from pathlib import Path


TOOLS_DIR = Path(__file__).resolve().parent


class WrapperLaunchContractTest(unittest.TestCase):
    def test_logged_server_helper_supports_retail_raw_checksum_passthrough(self) -> None:
        text = (TOOLS_DIR / "start_server_logged.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$EnableRetailRawChecksumPassthrough", text)
        self.assertIn("OPENNXT_ENABLE_RETAIL_RAW_CHECKSUM_PASSTHROUGH", text)
        self.assertIn("OPENNXT_DISABLE_CHECKSUM_OVERRIDE", text)

    def test_logged_server_helper_supports_retail_logged_out_js5_passthrough(self) -> None:
        text = (TOOLS_DIR / "start_server_logged.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$EnableRetailLoggedOutJs5Passthrough", text)
        self.assertIn("[switch]$DisableRetailLoggedOutJs5Passthrough", text)
        self.assertIn("OPENNXT_ENABLE_RETAIL_LOGGED_OUT_JS5_PASSTHROUGH", text)
        self.assertIn("[switch]$EnableLoggedOutJs5PrefetchTable", text)
        self.assertIn("OPENNXT_ENABLE_LOGGED_OUT_JS5_PREFETCH_TABLE", text)

    def test_runtime_cache_sync_uses_stdin_python_probe_for_sqlite_shape(self) -> None:
        text = (TOOLS_DIR / "sync_runescape_runtime_cache.ps1").read_text(encoding="utf-8")
        self.assertIn('connection = sqlite3.connect(f"file:{path}?mode=ro", uri=True)', text)
        self.assertIn('$raw = $pythonScript | & $pythonCommand.Source - $Path 2>$null', text)
        self.assertIn('"missing-reference-table"', text)

    def test_lobby_tls_helper_supports_retail_js5_upstream(self) -> None:
        text = (TOOLS_DIR / "launch_lobby_tls_terminator.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$AllowRetailJs5Upstream", text)
        self.assertIn('"--allow-retail-js5-upstream"', text)
        self.assertIn("[double]$SocketTimeout = 180", text)

        watchdog_text = (TOOLS_DIR / "keep_local_live_stack.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$AllowRetailJs5Upstream", watchdog_text)
        self.assertIn('$lobbyProxyArgs += "-AllowRetailJs5Upstream"', watchdog_text)
        self.assertIn('$hasMutex = $mutex.WaitOne(0, $false)', watchdog_text)
        self.assertIn('if ($hasMutex -and $null -ne $mutex) {', watchdog_text)

        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$AllowRetailJs5Upstream", client_text)
        self.assertIn('$lobbyProxyArgs["AllowRetailJs5Upstream"] = $true', client_text)
        self.assertIn('[switch]$DisableWatchdog', client_text)
        self.assertIn('$watchdogScript = Join-Path $PSScriptRoot "keep_local_live_stack.ps1"', client_text)
        self.assertIn('$watchdog = Start-Process `', client_text)
        self.assertIn('$watchdogArgs += "-AllowRetailJs5Upstream"', client_text)
        self.assertIn('WatchdogPid = if ($watchdog) { [int]$watchdog.Id } else { $null }', client_text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$AllowRetailJs5Upstream", live_text)
        self.assertIn('$lobbyProxyArgs += "-AllowRetailJs5Upstream"', live_text)
        self.assertIn('$watchdogArgs += "-AllowRetailJs5Upstream"', live_text)

    def test_client_only_launcher_starts_local_game_proxy_for_947_retail_route(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn('$gameProxyScript = Join-Path $PSScriptRoot "launch_game_tls_terminator.ps1"', text)
        self.assertIn('$tlsTerminateProxyScript = Join-Path $PSScriptRoot "tls_terminate_proxy.py"', text)
        self.assertIn('$contentBootstrapProxyScript = Join-Path $PSScriptRoot "tcp_proxy.py"', text)
        self.assertIn("$use947ContainedLocalBridgeRoute = $configuredClientBuild -ge 947 -and (", text)
        self.assertIn('$launchArg -like "*contentRouteRewrite=1*"', text)
        self.assertIn("$shouldLaunch947LobbyProxy = $configuredClientBuild -ge 947 -and ($use947RetailConfigRoute -or $use947ContainedLocalBridgeRoute)", text)
        self.assertIn("$shouldLaunch947ContentBootstrapProxy = $configuredClientBuild -ge 947 -and", text)
        self.assertIn('$launchArg -like "https://rs.config.runescape.com*"', text)
        self.assertIn('$launchArg -like "http://127.0.0.1:*"', text)
        self.assertIn('$launchArg -like "http://localhost*"', text)
        self.assertIn('function Get-ProxyProcessIdsForListenPort {', text)
        self.assertIn('$lobbyProxyPythonArgs = @(', text)
        self.assertIn('--tls-extra-mitm-host', text)
        self.assertIn('--allow-retail-js5-upstream', text)
        self.assertIn('$quotedLobbyProxyArgs = @($lobbyProxyPythonArgs | ForEach-Object { Quote-ProcessArgument $_ })', text)
        self.assertIn('$lobbyProxyLauncher = Start-Process `', text)
        self.assertIn('-RedirectStandardOutput $lobbyProxyOut `', text)
        self.assertIn('-RedirectStandardError $lobbyProxyErr `', text)
        self.assertIn('Write-ClientOnlyTrace ("lobby proxy launcher pid={0}" -f $lobbyProxyLauncher.Id)', text)
        self.assertIn('Get-ProxyProcessIdsForListenPort -ListenPort 443', text)
        self.assertIn("[regex]::Match($commandLine, '(?i)(?:^|\\s)--listen-port\\s+\"?(?<port>\\d+)\"?')", text)
        self.assertNotIn('$_.CommandLine -like "*$ListenPort*"', text)
        self.assertIn('Write-ClientOnlyTrace "lobby proxy launch dispatched"', text)
        self.assertIn('if ($shouldLaunch947LobbyProxy -and (Test-Path $lobbyProxyScript)) {', text)
        self.assertIn('$lobbyProxyProcessIds = @(Get-ListeningProcessIds -Ports @(443))', text)
        self.assertIn('Timed out waiting for the local lobby TLS terminator on port 443. stderr={0}', text)
        self.assertIn('$gameProxyLauncherArgs = @(', text)
        self.assertIn('$gameProxyLauncher = Start-Process `', text)
        self.assertIn('$gameProxyProcessIds = @(Get-ListeningProcessIds -Ports @([int]$gamePort))', text)
        self.assertIn('$gameProxyReady = Wait-ListeningPorts -Ports @([int]$gamePort) -TimeoutSeconds 30', text)
        self.assertIn('throw ("Timed out waiting for the local game TLS proxy on port {0}." -f $gamePort)', text)
        self.assertIn("GameProxyPortReady = [bool]$gameProxyReady", text)
        self.assertIn('Write-ClientOnlyTrace "content bootstrap proxy launch begin"', text)
        self.assertIn('$shouldLaunch947ContentBootstrapProxy -and', text)
        self.assertIn('Get-ProxyProcessIdsForListenPort -ListenPort 80', text)
        self.assertIn('Cannot start the local content bootstrap proxy on port 80 because it is already in use', text)
        self.assertIn('$contentBootstrapProxyArgs = @(', text)
        self.assertIn('"--listen-port"', text)
        self.assertIn('"80"', text)
        self.assertIn('$quotedContentBootstrapProxyArgs = @($contentBootstrapProxyArgs | ForEach-Object { Quote-ProcessArgument $_ })', text)
        self.assertIn('$contentBootstrapProxyLauncher = Start-Process `', text)
        self.assertIn('-RedirectStandardOutput $contentBootstrapProxyOut `', text)
        self.assertIn('-RedirectStandardError $contentBootstrapProxyErr `', text)
        self.assertIn('Timed out waiting for the local content bootstrap proxy on port 80.', text)
        self.assertIn('ContentBootstrapProxyScript = if ($contentBootstrapProxyLauncher) { $contentBootstrapProxyScript } else { $null }', text)
        self.assertIn('ContentBootstrapProxyPortReady = [bool]$contentBootstrapProxyReady', text)

    def test_launchers_can_skip_runtime_cache_sync_for_clean_live_metadata_repros(self) -> None:
        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$SkipRuntimeCacheSync", client_text)
        self.assertIn('$runtimeAutoSkipCacheSync947Retail = $configuredClientBuild -ge 947 -and $useDirectPatchedRs2Client -and (', client_text)
        self.assertIn('[string]::Equals($resolvedDownloadMetadataSource, "live", [System.StringComparison]::OrdinalIgnoreCase)', client_text)
        self.assertIn("runtime cache sync auto-skipped for 947 live-metadata direct-patched path", client_text)
        self.assertIn("-not $runtimeCacheSyncSkippedEffective -and $configuredClientBuild -ge 947", client_text)
        self.assertIn("RuntimeCacheSyncSkipped = [bool]$runtimeCacheSyncSkippedEffective", client_text)
        self.assertIn("RuntimeCacheSyncAutoSkipped = [bool]$runtimeAutoSkipCacheSync947Retail", client_text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$SkipRuntimeCacheSync", live_text)
        self.assertIn("$runtimeAutoSkipCacheSync947Retail = $configuredClientBuild -ge 947 -and $runtimeUsesRetailStartupConfig -and $prefer947PatchedDirectClient", live_text)
        self.assertIn("runtime cache sync auto-skipped for 947 retail-shaped direct-patched path", live_text)
        self.assertIn("-not $runtimeCacheSyncSkippedEffective -and $configuredClientBuild -ge 947", live_text)
        self.assertIn("RuntimeCacheSyncSkipped = [bool]$runtimeCacheSyncSkippedEffective", live_text)
        self.assertIn("RuntimeCacheSyncAutoSkipped = [bool]$runtimeAutoSkipCacheSync947Retail", live_text)

    def test_direct_patch_launchers_use_summary_handshake(self) -> None:
        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn('$directPatchStdout = Join-Path $root "data\\\\debug\\\\direct-rs2client-patch\\\\latest-live.stdout.log"', live_text)
        self.assertIn('$directPatchStderr = Join-Path $root "data\\\\debug\\\\direct-rs2client-patch\\\\latest-live.stderr.log"', live_text)
        self.assertIn('$directPatchHelper = Start-Process `', live_text)
        self.assertIn('-RedirectStandardOutput $directPatchStdout `', live_text)
        self.assertIn('-RedirectStandardError $directPatchStderr `', live_text)
        self.assertIn('Write-LaunchTrace ("direct patch helper start exe={0}" -f $ClientExePath)', live_text)
        self.assertIn('Write-LaunchTrace ("direct patch helper summary ready helperPid={0}" -f $directPatchHelper.Id)', live_text)
        self.assertIn('Write-LaunchTrace ("direct patch helper summary loaded helperPid={0} pid={1} stage={2}" -f $directPatchHelper.Id, $directPatchLaunchSummary.pid, $summaryStage)', live_text)
        self.assertIn('Write-LaunchTrace ("direct patch helper client resolved helperPid={0} pid={1}" -f $directPatchHelper.Id, $client.Id)', live_text)
        self.assertIn('Write-LaunchTrace ("launch state written file={0}" -f $launchStateFile)', live_text)

        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn('$directPatchStdout = Join-Path $root "data\\\\debug\\\\direct-rs2client-patch\\\\latest-client-only.stdout.log"', client_text)
        self.assertIn('$directPatchStderr = Join-Path $root "data\\\\debug\\\\direct-rs2client-patch\\\\latest-client-only.stderr.log"', client_text)
        self.assertIn('$helperProcess = Start-Process `', client_text)
        self.assertIn('-RedirectStandardOutput $directPatchStdout `', client_text)
        self.assertIn('-RedirectStandardError $directPatchStderr `', client_text)
        self.assertIn('$serverLaunchParams = @{}', client_text)
        self.assertIn('$serverLaunchParams.EnableRetailRawChecksumPassthrough = $true', client_text)
        self.assertIn('if (-not $AllowRetailJs5Upstream) {', client_text)
        self.assertIn('$serverLaunchParams.EnableRetailLoggedOutJs5Passthrough = $true', client_text)
        self.assertIn('$serverLaunchParams.DisableRetailLoggedOutJs5Passthrough = $true', client_text)
        self.assertIn('$serverLaunchParams.SkipHttpFileVerification = $true', client_text)
        self.assertIn('Write-ClientOnlyTrace ("server launch params={0}" -f (($serverLaunchParams.GetEnumerator() | Sort-Object Name | ForEach-Object { "{0}={1}" -f $_.Name, $_.Value }) -join ","))', client_text)
        self.assertIn('$serverLaunchOutput = & $serverLauncherScript @serverLaunchParams', client_text)
        self.assertIn("if (-not $AllowRetailJs5Upstream) {", live_text)
        self.assertIn('OPENNXT_ENABLE_RETAIL_LOGGED_OUT_JS5_PASSTHROUGH=1', live_text)
        self.assertIn('OPENNXT_ENABLE_RETAIL_LOGGED_OUT_JS5_PASSTHROUGH=0', live_text)
        self.assertNotIn('$serverLaunchArgs += "-EnableLoggedOutJs5PrefetchTable"', client_text)
        self.assertIn('Direct patch launch retrying without pre-resume Frida startup hook or startup redirects', client_text)

    def test_direct_947_startup_contract_matches_launch_mode(self) -> None:
        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn("Match the live launcher: keep the visible 947 startup contract", client_text)
        self.assertIn("retail-shaped and contain it with redirects plus the local 443", client_text)
        self.assertIn('"https://rs.config.runescape.com/k=5/l=0/jav_config.ws?binaryType=6&hostRewrite=0&lobbyHostRewrite=0&contentRouteRewrite=0&worldUrlRewrite=0&codebaseRewrite=0&gameHostRewrite=0&baseConfigSource=live&liveCache=1&downloadMetadataSource=original"', client_text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "contentRouteRewrite" -Value "1"', client_text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "worldUrlRewrite" -Value "1"', client_text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "codebaseRewrite" -Value "1"', client_text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "baseConfigSource" -Value "live"', client_text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "liveCache" -Value "1"', client_text)
        self.assertIn('"original"', client_text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("Keep the visible 947 direct startup contract retail-shaped", live_text)
        self.assertIn("base-config + original metadata pair", live_text)
        self.assertIn("Final safety net: the direct 947 retail-shaped startup path should keep", live_text)
        self.assertIn('"https://rs.config.runescape.com/k=5/l=0/jav_config.ws?binaryType=6&hostRewrite=0&lobbyHostRewrite=0&contentRouteRewrite=0&worldUrlRewrite=0&codebaseRewrite=0&gameHostRewrite=0&baseConfigSource=live&liveCache=1&downloadMetadataSource=original"', live_text)
        self.assertIn('[string]::Equals((Get-UriHostName -Value $effectiveLaunchArg), "rs.config.runescape.com", [System.StringComparison]::OrdinalIgnoreCase)', live_text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "gamePortOverride"', live_text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "contentRouteRewrite" -Value "0"', live_text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "worldUrlRewrite" -Value "0"', live_text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "codebaseRewrite" -Value "0"', live_text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "baseConfigSnapshotPath"', live_text)
        self.assertIn('"original"', live_text)

    def test_direct_947_launch_arg_restores_local_bridge_contract(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        match = re.search(
            r"function Convert-To947DirectClientLaunchArg \{(?P<body>.*?)^\}",
            text,
            re.MULTILINE | re.DOTALL,
        )
        self.assertIsNotNone(match)
        body = match.group("body")
        self.assertIn('Set-QueryParameter -Url $Url -Name "contentRouteRewrite" -Value "1"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "worldUrlRewrite" -Value "1"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "codebaseRewrite" -Value "1"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "baseConfigSource" -Value "live"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "liveCache" -Value "1"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "gamePortOverride" -Value $GamePort', body)
        self.assertNotIn('Remove-QueryParameter -Url $updated -Name "baseConfigSource"', body)
        self.assertNotIn('Remove-QueryParameter -Url $updated -Name "liveCache"', body)

    def test_direct_947_no_frida_loopback_launch_arg_preserves_explicit_contract_shape(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        match = re.search(
            r"function Convert-To947ContainedLoopbackLaunchArg \{(?P<body>.*?)^\}",
            text,
            re.MULTILINE | re.DOTALL,
        )
        self.assertIsNotNone(match)
        body = match.group("body")
        self.assertIn('Set-QueryParameter -Url $Url -Name "contentRouteRewrite" -Value "1"', body)
        self.assertIn('Get-QueryParameterValue -Url $updated -Name "worldUrlRewrite"', body)
        self.assertIn('Get-QueryParameterValue -Url $updated -Name "codebaseRewrite"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "worldUrlRewrite" -Value "0"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "codebaseRewrite" -Value "0"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "baseConfigSource" -Value "live"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "liveCache" -Value "1"', body)
        self.assertIn('Get-QueryParameterValue -Url $updated -Name "downloadMetadataSource"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "downloadMetadataSource" -Value "live"', body)

    def test_no_frida_fallback_uses_milder_loopback_helper(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn(
            '$startupConfigSnapshotRoot = Join-Path $root "data\\\\debug\\\\startup-config-snapshots\\\\947-client-only"',
            text,
        )
        self.assertIn(
            '$startupConfigSnapshotPath = Join-Path $startupConfigSnapshotRoot ("startup-config-{0}.ws" -f $startupConfigSnapshotRunId)',
            text,
        )
        self.assertIn(
            '$loopbackLaunchArg = Convert-ToLoopbackJavConfigUrl -Url (Convert-To947ContainedLoopbackLaunchArg -Url $launchArg -GamePort $gamePort) -HttpPort ([int]$httpPort)',
            text,
        )
        self.assertIn(
            '"947 contained route using hosts override because Frida import is unavailable hosts={0}" -f',
            text,
        )
        self.assertIn(
            '"947 contained route using local loopback bridge because Frida import is unavailable launchArg={0}" -f',
            text,
        )
        self.assertIn(
            'function Get-947PreferredStartupWorldHostFromConfigContent {',
            text,
        )
        self.assertIn(
            '$requestedWorldHost = Get-947PreferredStartupWorldHostFromConfigContent -ConfigContent $startupConfigContent',
            text,
        )
        self.assertIn(
            '$loopbackLaunchArg = Set-QueryParameter -Url $loopbackLaunchArg -Name "requestedWorldHost" -Value $requestedWorldHost',
            text,
        )
        self.assertIn(
            '$loopbackLaunchArg = Set-QueryParameter -Url $loopbackLaunchArg -Name "baseConfigSnapshotPath" -Value $startupConfigSnapshotPath',
            text,
        )
        self.assertIn(
            '"947 contained route loopback requested world host={0}" -f $requestedWorldHost',
            text,
        )
        self.assertIn(
            '"947 contained route loopback startup snapshot={0}" -f $startupConfigSnapshotPath',
            text,
        )
        self.assertIn(
            '$baseUrl = "http://127.0.0.1:$HttpPort$preservedPath"',
            text,
        )
        self.assertIn(
            'if ($secureRetailHostsOverrideHosts.Count -eq 0) {',
            text,
        )

    def test_direct_patch_launch_can_fallback_to_original_when_policy_blocks_patched_client(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn(
            'Direct patch launch retrying with original client because the staged client was blocked by Application Control',
            text,
        )
        self.assertIn(
            '$usedOriginalClientFallback = $true',
            text,
        )
        self.assertIn(
            '$attemptClientExePath = $originalClientExe',
            text,
        )
        self.assertIn(
            'UsedOriginalClientFallback = $usedOriginalClientFallback',
            text,
        )
        self.assertIn(
            'AutoSelectedOriginalClient = if ($directLaunch) { [bool]$directLaunch.UsedOriginalClientFallback } else { $false }',
            text,
        )

    def test_explicit_947_config_urls_are_not_silently_rewritten_back_to_retail(self) -> None:
        client_only_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn('$configUrlExplicit = $PSBoundParameters.ContainsKey("ConfigUrl") -and -not [string]::IsNullOrWhiteSpace($ConfigUrl)', client_only_text)
        self.assertIn("respect an explicit caller-provided startup contract", client_only_text)
        self.assertIn("if (-not $configUrlExplicit) {", client_only_text)
        self.assertIn("if ($prefer947PatchedDirectClient -and -not $configUrlExplicit) {", client_only_text)
        self.assertIn('$gameBackendPort = Get-TomlTableScalarValue -Path $serverConfigPath -TableName "networking.ports" -Key "gameBackend"', client_only_text)
        self.assertIn('if ($gameBackendPort -eq $gamePort) {', client_only_text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn('$configUrlOverrideExplicit = $PSBoundParameters.ContainsKey("ConfigUrlOverride") -and -not [string]::IsNullOrWhiteSpace($ConfigUrlOverride)', live_text)
        self.assertIn("preserve an explicit ConfigUrlOverride", live_text)
        self.assertIn("if (-not $configUrlOverrideExplicit) {", live_text)

    def test_947_world_fleet_hosts_are_explicit_not_wildcard(self) -> None:
        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")

        for text in (client_text, live_text):
            self.assertIn('"content*.runescape.com"', text)
            self.assertIn('"world*.runescape.com"', text)
            self.assertIn('"lobby*.runescape.com"', text)
            self.assertNotIn('foreach ($worldId in 1..100)', text)
            self.assertNotIn('$hosts += "world2a.runescape.com"', text)
            self.assertNotIn('$hosts += "world210.runescape.com"', text)

    def test_947_startup_redirect_contracts_match_launch_mode(self) -> None:
        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$Disable947JumpBypassGuards", client_text)
        self.assertIn("$enable947StartupResolveRedirects = $configuredClientBuild -ge 947 -and $use947RetailConfigRoute -and $Force947StartupRouteRedirects", client_text)
        self.assertIn("$enable947ContainedRouteRedirects = $configuredClientBuild -ge 947 -and", client_text)
        self.assertIn("$shouldLaunch947LobbyProxy -and", client_text)
        self.assertIn("-not $Force947StartupRouteRedirects", client_text)
        self.assertIn("if ($enable947StartupResolveRedirects) {", client_text)
        self.assertIn("elseif ($enable947ContainedRouteRedirects) {", client_text)
        self.assertIn("function Test-947WorldHostName {", client_text)
        self.assertIn("function Test-947LobbyHostName {", client_text)
        self.assertIn("function Test-947ContentHostName {", client_text)
        self.assertIn("function Test-947StartupHostShouldStayRetail {", client_text)
        self.assertIn("function Test-947SecureStartupRedirectHost {", client_text)
        self.assertIn("Get-947StartupRouteHostsFromConfigContent -ConfigContent $startupConfigContent) | Where-Object { Test-947SecureStartupRedirectHost -HostName $_ }", client_text)
        self.assertIn("@(Get-947SecureRetailWorldFleetHosts)", client_text)
        self.assertNotIn('Where-Object { $Force947StartupRouteRedirects -or -not (Test-947StartupHostShouldStayRetail -HostName $_) }', client_text)
        self.assertIn('$pythonArgs += "--force-secure-retail-startup-redirects"', client_text)
        self.assertIn("if ($enable947StartupResolveRedirects) {", client_text)
        self.assertIn("Only explicit", client_text)
        self.assertIn("Match the last clean contained direct baseline", client_text)
        self.assertIn("Direct/local-rewrite contracts need real host containment too", client_text)
        self.assertIn('Write-ClientOnlyTrace ("947 contained route resolve redirects={0}" -f ($resolveRedirectSpecs -join ","))', client_text)
        self.assertIn("if (-not $Disable947JumpBypassGuards.IsPresent) {", client_text)
        self.assertIn("Disable947JumpBypassGuards = [bool]$Disable947JumpBypassGuards.IsPresent", client_text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x590c58:0x590c81"', client_text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x2ab698:0x2ab7f7"', client_text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x3699b2:0x3699f2"', client_text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x7a3bc2:0x7a3bff"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59034d:0x5903c6"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59c1ea:0x59c21b"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59c2a0:0x59c64f"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590c72:0x590dba"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590de8:0x590ec6"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590ec9:0x590eda"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590ccb:0x590cf1"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590cf1:0x590dcb"', client_text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x5955a2"', client_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59707d:0x597087"', client_text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$Disable947JumpBypassGuards", live_text)
        self.assertIn("$enable947StartupResolveRedirects = $configuredClientBuild -ge 947 -and $use947RetailConfigHost -and $script:UseContentTlsRoute -and $Force947StartupRouteRedirects", live_text)
        self.assertIn("if ($enable947StartupResolveRedirects) {", live_text)
        self.assertIn("function Test-947SecureStartupRedirectHost {", live_text)
        self.assertIn("(@($startupRouteHosts) | Where-Object { Test-947SecureStartupRedirectHost -HostName $_ }) +", live_text)
        self.assertIn("@(Get-947SecureRetailWorldFleetHosts)", live_text)
        self.assertIn('$rewriteArgs += "--force-secure-retail-startup-redirects"', live_text)
        self.assertIn("if ($enable947StartupResolveRedirects) {", live_text)
        self.assertIn("forced-startup experiments; the default path keeps them", live_text)
        self.assertIn("Match the last clean contained direct baseline", live_text)
        self.assertIn("if (-not $Disable947JumpBypassGuards.IsPresent) {", live_text)
        self.assertIn("Disable947JumpBypassGuards = [bool]$Disable947JumpBypassGuards.IsPresent", live_text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x590c58:0x590c81"', live_text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x2ab698:0x2ab7f7"', live_text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x3699b2:0x3699f2"', live_text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x7a3bc2:0x7a3bff"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59034d:0x5903c6"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59c1ea:0x59c21b"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59c2a0:0x59c64f"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590c72:0x590dba"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590de8:0x590ec6"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590ec9:0x590eda"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590ccb:0x590cf1"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590cf1:0x590dcb"', live_text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x5955a2"', live_text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59707d:0x597087"', live_text)

    def test_client_only_launcher_defaults_to_direct_patched_for_947(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn("function Quote-ProcessArgument", text)
        self.assertIn("[switch]$Force947StartupRouteRedirects", text)
        self.assertIn("[switch]$Enable947LoadingStateBuilderTrace", text)
        self.assertIn("[switch]$Force947LoadingStateRebuild", text)
        self.assertIn("[switch]$Force947RecordStateFromType0", text)
        self.assertIn('$quotedPythonArgs = @($pythonArgs | ForEach-Object { Quote-ProcessArgument $_ })', text)
        self.assertIn("launch_runescape_wrapper_rewrite.py", text)
        self.assertIn("[switch]$UseRuneScapeWrapper", text)
        self.assertIn('$originalClientExe = Join-Path $root ("data\\\\clients\\\\{0}\\\\win64c\\\\original\\\\rs2client.exe" -f $configuredClientBuild)', text)
        self.assertNotIn('Sync-InstalledRuneScapeRuntimeFile -SourcePath $installedGameClientExe -ClientDirectory $ClientDirectory -FileName "rs2client.exe"', text)
        self.assertIn("$prefer947OriginalClientFamily", text)
        self.assertIn('[string]::Equals($effectiveClientVariant, "original", [System.StringComparison]::OrdinalIgnoreCase)', text)
        self.assertIn('AutoSelectedOriginalClient = if ($directLaunch) { [bool]$directLaunch.UsedOriginalClientFallback } else { $false }', text)
        self.assertIn("$selectedRuneScapeWrapper = Join-Path $clientDir \"RuneScape.exe\"", text)
        self.assertIn("$localChildExe = Join-Path $clientDir \"rs2client.exe\"", text)
        self.assertIn("$explicitClientExeOverride = -not [string]::IsNullOrWhiteSpace($ClientExeOverride)", text)
        self.assertIn("Sync-InstalledRuneScapeWrapper -ClientDirectory $clientDir", text)
        self.assertIn("$prefer947PatchedDirectClient", text)
        self.assertIn("-and -not $prefer947PatchedDirectClient", text)
        self.assertNotIn('-not [string]::Equals($effectiveClientVariant, "original"', text)
        self.assertIn("$existingDownloadMetadataSource = Get-QueryParameterValue -Url $ConfigUrl -Name \"downloadMetadataSource\"", text)
        self.assertIn("Remove-QueryParameter", text)
        self.assertIn("$effectiveClientVariant.Trim().ToLowerInvariant()", text)
        self.assertIn('[string]::Equals((Get-UriHostName -Value $ConfigUrl), "rs.config.runescape.com", [System.StringComparison]::OrdinalIgnoreCase)', text)
        self.assertIn('"live"', text)
        self.assertIn('ClientVariant = "patched"', text)
        self.assertIn("$useDirectPatchedRs2Client", text)
        self.assertIn("(($launchViaRuneScapeWrapper -or $useDirectPatchedRs2Client) -and $configuredClientBuild -ge 947)", text)
        self.assertIn("if ($autoManageGraphicsCompat -and ($launchViaRuneScapeWrapper -or $useDirectPatchedRs2Client) -and (Test-Path $launcherPreferencesScript))", text)
        self.assertIn("$directPatchStartupHookOutput = Join-Path $root \"data\\\\debug\\\\direct-rs2client-patch\\\\latest-client-only-hook.jsonl\"", text)
        self.assertIn("$directPatchProducerOutputRoot = Join-Path $root \"data\\\\debug\\\\prelogin-producer-947-direct-helper-client-only\"", text)
        self.assertIn("if ($Force947RecordStateFromType0) {", text)
        self.assertIn('$directPatchExtraArgs += "--resource-gate-output-root"', text)
        self.assertIn('$directPatchExtraArgs += $directPatchResourceGateOutputRoot', text)
        self.assertIn('$directPatchExtraArgs += "--resource-gate-force-recordstate-from-type0"', text)
        self.assertIn("$directPatchLoadingStateOutputRoot = Join-Path $root \"data\\\\debug\\\\loading-state-builder-947-direct-helper-client-only\"", text)
        self.assertIn("--startup-hook-output", text)
        self.assertIn("[switch]$VerboseStartupHook", text)
        self.assertIn("--startup-hook-verbose", text)
        self.assertIn('$directPatchExtraArgs += "--loading-state-output-root"', text)
        self.assertNotIn('$directPatchExtraArgs += "--producer-output-root"', text)
        self.assertIn('$directPatchInlinePatchOffsets += "0x590cf4"', text)
        self.assertIn('"https://rs.config.runescape.com/k=5/l=0/jav_config.ws?binaryType=6&hostRewrite=0&lobbyHostRewrite=0&contentRouteRewrite=0&worldUrlRewrite=0&codebaseRewrite=0&gameHostRewrite=0&baseConfigSource=live&liveCache=1&downloadMetadataSource=original"', text)
        self.assertIn("Convert-ToLoopbackJavConfigUrl", text)
        self.assertIn('gameHostRewrite=0', text)
        self.assertIn("keep the 947 wrapper startup contract", text)
        self.assertIn('Set-QueryParameter -Url $launchArg -Name "codebaseRewrite" -Value "0"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "contentRouteRewrite" -Value "1"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "worldUrlRewrite" -Value "1"', text)
        self.assertIn('$use947RetailConfigRoute = $ConfigUrl -like "https://rs.config.runescape.com*"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "codebaseRewrite" -Value "1"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "codebaseRewrite" -Value "1"', text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "gamePortOverride"', text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "baseConfigSource"', text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "liveCache"', text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "baseConfigSnapshotPath"', text)
        self.assertIn("Get-947StartupConfigContent", text)
        self.assertIn("Get-947StartupParamMapFromConfigContent", text)
        self.assertIn("Convert-947StartupConfigToParamPairArgs", text)
        self.assertIn("Save-947StartupConfigSnapshot", text)
        self.assertIn("Get-947StartupRouteHostsFromConfigContent", text)
        self.assertIn("Get-947StartupWorldMitmHostsFromConfigContent", text)
        self.assertIn('$startupLauncherToken947 = "A234"', text)

    def test_client_only_wrapper_path_revalidates_installed_runtime_after_spawn(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn('$installedRuntimePostLaunchVerifySummary = Join-Path $root "data\\\\debug\\\\wrapper-spawn-rewrite\\\\latest-installed-runtime-post-launch-check.json"', text)
        self.assertIn('"--check-only"', text)
        self.assertIn('Wrapper child stayed on installed runtime path, but post-launch verification drifted; forcing direct patched fallback', text)
        self.assertIn('InstalledRuntimePostLaunchVerifySummary = if ($installedRuntimePostLaunchVerifyResult)', text)
        self.assertIn('InstalledRuntimePostLaunchVerifyInstalledReadyAfter = if ($installedRuntimePostLaunchVerifyResult)', text)
        self.assertIn('$paramPairArgs947 = @(Convert-947StartupConfigToParamPairArgs -ConfigContent $startupConfigContent -LauncherToken $startupLauncherToken947)', text)
        self.assertIn('$shouldUse947DirectParamPairArgs = $false', text)
        self.assertIn('if ($shouldUse947DirectParamPairArgs) {', text)
        self.assertIn('$use947DirectParamPairArgs = $false', text)
        self.assertIn('} elseif ($effectiveUseConfigUriArg -and -not $use947DirectParamPairArgs) {', text)
        self.assertIn('[void]$arguments.Add("launcher")', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "gameHostRewrite" -Value "0"', text)
        self.assertIn("--rsa-config", text)
        self.assertIn("--js5-rsa-source-exe", text)
        self.assertIn("set_windows_gpu_preference.ps1", text)
        self.assertIn('launch_lobby_tls_terminator.ps1', text)
        self.assertIn("sync_runescape_runtime_cache.ps1", text)
        self.assertIn("sync_runescape_installed_runtime.py", text)
        self.assertIn("function Quote-CmdArgument", text)
        self.assertIn("function Wait-ListeningPorts", text)
        self.assertIn('$lobbyProxyReady = Wait-ListeningPorts -Ports @(443) -TimeoutSeconds 30', text)
        self.assertIn('throw "Timed out waiting for the local lobby TLS terminator on port 443."', text)
        self.assertIn("LobbyProxyPortReady = [bool]$lobbyProxyReady", text)
        self.assertIn("$runtimePromoteToFullSync", text)
        self.assertIn("HotStubArchiveIdsBefore", text)
        self.assertIn("HotMissingReferenceTableArchiveIdsBefore", text)
        self.assertIn("CopiedHotArchiveIds", text)
        self.assertIn("$runtimeCopiedHotArchiveIds", text)
        self.assertIn("function Get-RuntimeArchiveSqliteShape", text)
        self.assertIn("$raw = $pythonScript | & $pythonCommand.Source - $Path 2>$null", text)
        self.assertIn("function Test-RuntimeArchiveHasMissingReferenceTable", text)
        self.assertIn("$runtimeUsesRetailStartupConfig = $configuredClientBuild -ge 947 -and $use947RetailConfigRoute", text)
        self.assertIn("$runtimePromoteToFullSync = (", text)
        self.assertIn("$runtimeTargetArchiveCount.Count -lt $runtimeSourceFiles.Count -or", text)
        self.assertIn("$runtimeHotStubArchiveIds.Count -gt 0 -or", text)
        self.assertIn("$runtimeHotMissingReferenceTableArchiveIds.Count -gt 0", text)
        self.assertIn("if ($runtimeHotArchiveParityMismatchIds.Count -gt 0) {", text)
        self.assertIn("$runtimePromoteToFullSync = $true", text)
        self.assertIn("$runtimeMissingHotArchiveIds = @(", text)
        self.assertIn("$runtimeHotMissingReferenceTableArchiveIds = @()", text)
        self.assertIn("$runtimeHotMissingReferenceTableArchiveIds = @(", text)
        self.assertIn("$runtimeClientManagedHotArchiveSet = $configuredClientBuild -ge 947 -and $runtimeUsesRetailStartupConfig -and $useDirectPatchedRs2Client -and $runtimeMissingHotArchiveIds.Count -eq 0 -and $runtimeHotMissingReferenceTableArchiveIds.Count -eq 0", text)
        self.assertIn("$runtimeForceRetailRefreshHotArchiveSet = $false", text)
        self.assertIn("tearing down the runtime hot archive", text)
        self.assertIn("$runtimeShouldPreserveHotArchiveSet = (", text)
        self.assertIn("$runtimeForceRetailRefreshHotArchiveSet -or", text)
        self.assertIn('if ($runtimeShouldPreserveHotArchiveSet) {', text)
        self.assertIn('$runtimeCacheSyncParameters["SkipJs5Archives"] = $runtimeHotArchiveIds947', text)
        self.assertIn('if ((-not $runtimeClientManagedHotArchiveSet) -and (-not $runtimeForceRetailRefreshHotArchiveSet)) {', text)
        self.assertIn('$runtimeCacheSyncParameters["ValidateSkippedArchives"] = $true', text)
        self.assertIn('$runtimeShouldPreserveHotArchiveSet -and', text)
        self.assertIn('-not $runtimeClientManagedHotArchiveSet -and', text)
        self.assertIn('-not $runtimeForceRetailRefreshHotArchiveSet -and', text)
        self.assertIn('$runtimeHotStubArchiveIds.Count -gt 0', text)
        self.assertIn('$runtimeCacheSyncParameters["RescueSkippedBootstrapStubs"] = $true', text)
        self.assertIn("$runtimeHotStubArchiveIds = @()", text)
        self.assertIn("$runtimeShouldPreserveHotArchiveSet = $false", text)
        self.assertIn("$runtimeShouldAutoRepairHotCache947 = $configuredClientBuild -ge 947 -and (", text)
        self.assertIn('($runtimeForceRetailRefreshHotArchiveSet -and $runtimeShouldPreserveHotArchiveSet) -or', text)
        self.assertIn('($runtimeShouldPreserveHotArchiveSet -and -not $runtimeClientManagedHotArchiveSet -and ($runtimeHotStubArchiveIds.Count -gt 0 -or $runtimeHotMissingReferenceTableArchiveIds.Count -gt 0))', text)
        self.assertIn('"auto-hot-missing-reference-table-quarantine"', text)
        self.assertIn("$runtimeHotCacheRepairArchiveIds", text)
        self.assertIn("} elseif ($runtimeForceRetailRefreshHotArchiveSet) {", text)
        self.assertIn("@($runtimeHotArchiveIds947)", text)
        self.assertIn("} elseif ($runtimeShouldAutoRepairHotCache947) {", text)
        self.assertIn("@($runtimeHotStubArchiveIds) +", text)
        self.assertIn("@($runtimeHotMissingReferenceTableArchiveIds)", text)
        self.assertIn("($RepairRuntimeHotCache.IsPresent -or $runtimeShouldAutoRepairHotCache947) -and", text)
        self.assertNotIn("full-sync-copied-hot-archives", text)
        self.assertIn('$runtimeSyncMode = if ($runtimePromoteToFullSync) { "full" } else { "seed-missing" }', text)
        self.assertIn('SyncMode -NotePropertyValue $runtimeSyncMode', text)
        self.assertIn("$runtimeSyncLocalDir = $clientDir", text)
        self.assertIn('@(\"original\", \"patched\", \"compressed\") -contains $resolvedDownloadMetadataSource', text)
        self.assertIn('PSBoundParameters.ContainsKey("DownloadMetadataSource")', text)
        self.assertIn("Get-QueryParameterValue", text)
        self.assertIn("Remove-QueryParameter", text)
        self.assertIn("RuntimeCacheSyncSummary", text)
        self.assertIn("RuntimeCacheSyncCopiedArchives", text)
        self.assertIn("RuntimeCacheSyncCopiedHotArchives", text)
        self.assertIn("RuntimeHotCacheRepairAutoTriggered", text)
        self.assertIn("RuntimeHotCacheRepairArchiveIds", text)
        self.assertIn("Sync-RetailHostsOverride", text)
        self.assertIn("Test-HostsFileWriteAccess", text)
        self.assertIn("$script:ConfiguredTlsExtraMitmHosts = @()", text)
        self.assertIn("$script:ConfiguredTlsExtraMitmHosts", text)
        self.assertIn("$startupRouteHosts = @()", text)
        self.assertIn('if ($configuredClientBuild -ge 947 -and $use947RetailConfigRoute) {', text)
        self.assertIn('if ($enable947StartupResolveRedirects) {', text)
        self.assertIn('Get-947StartupRouteHostsFromConfigContent -ConfigContent $startupConfigContent', text)
        self.assertIn("Get-947SecureRetailWorldFleetHosts", text)
        self.assertIn("Test-947WorldHostName", text)
        self.assertIn("Test-947StartupHostShouldStayRetail", text)
        self.assertIn("$startupRedirectHosts = @(", text)
        self.assertIn('(Get-947SecureRetailWorldFleetHosts)', text)
        self.assertIn('Where-Object { $_ -notin @("localhost", "127.0.0.1", "::1", "rs.config.runescape.com") }', text)
        self.assertNotIn('Where-Object { $Force947StartupRouteRedirects -or -not (Test-947StartupHostShouldStayRetail -HostName $_) }', text)
        self.assertIn('($startupRedirectHosts | ForEach-Object { "{0}={1}" -f $_, $defaultMitmPrimaryHost })', text)
        self.assertIn("--resolve-redirect", text)
        self.assertGreaterEqual(text.count("--resolve-redirect"), 2)
        self.assertNotIn('"rs.config.runescape.com=localhost"', text)
        self.assertNotIn('($startupRouteHosts | ForEach-Object { "{0}={1}" -f $_, $defaultMitmPrimaryHost })', text)
        self.assertIn("InstalledRuntimeSyncSummary", text)
        self.assertIn("InstalledRuntimeSyncLocalDir", text)
        self.assertIn("InstalledRuntimeSyncCopiedFiles", text)
        self.assertIn("InstalledRuntimeSyncInstalledReadyAfter", text)
        self.assertIn("InstalledRuntimeSyncFailedFiles", text)
        self.assertIn('"--timeout-seconds"', text)
        self.assertIn('"30"', text)
        self.assertIn('"--config-file"', text)
        self.assertIn('$startupConfigSnapshotReady = $false', text)
        self.assertIn('Remove-Item $startupConfigSnapshotPath -Force -ErrorAction SilentlyContinue', text)
        self.assertIn("(Test-Path $startupConfigSnapshotPath)", text)
        self.assertIn('--rewrite-config-file', text)
        self.assertIn('$pythonArgs += $startupConfigSnapshotPath', text)
        self.assertIn("ProgramData runtime files still do not match the live manifest.", text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "worldUrlRewrite" -Value "1"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "baseConfigSource" -Value "live"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "liveCache" -Value "1"', text)
        self.assertIn("--patch-jump-bypass", text)
        self.assertIn("--patch-inline-offset", text)
        self.assertIn("--child-exe-override", text)
        self.assertIn("--accepted-child-exe", text)
        self.assertIn("--rewrite-scope", text)
        self.assertIn('"all"', text)
        self.assertIn("0x590001", text)
        self.assertIn("0x590321", text)
        self.assertIn("0x5916c3", text)
        self.assertIn("0x5916f0", text)
        self.assertIn("0x591712", text)
        self.assertIn("0x591719", text)
        self.assertIn("0x5919e3", text)
        self.assertIn("0x591a10", text)
        self.assertIn("0x591a32", text)
        self.assertIn("0x591a39", text)
        self.assertNotIn('$wrapperInlinePatchOffsets += "0x590cf4"', text)
        self.assertNotIn('$wrapperInlinePatchOffsets += "0x58ff0f"', text)
        self.assertNotIn('$wrapperInlinePatchOffsets += "0x594a41"', text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn('set "OPENNXT_ENABLE_RETAIL_RAW_CHECKSUM_PASSTHROUGH=1"', live_text)
        self.assertIn('set "OPENNXT_ENABLE_RETAIL_LOGGED_OUT_JS5_PASSTHROUGH=1"', live_text)
        self.assertIn("--js5-rsa-source-exe", live_text)
        self.assertIn("0x594d61", text)
        self.assertIn('$wrapperJumpBypassSpecs += "0x59002d:0x5900a5"', text)
        self.assertIn('$wrapperJumpBypassSpecs += "0x5902d5:0x5903bd"', text)
        self.assertNotIn("0x59034d:0x5903c6", text)
        self.assertIn("0x590c58:0x590c81", text)
        self.assertIn("0x3699b2:0x3699f2", text)
        self.assertNotIn("0x59c1ea:0x59c21b", text)
        self.assertNotIn("0x59c2a0:0x59c64f", text)
        self.assertNotIn("0x590c72:0x590dba", text)
        self.assertNotIn("0x590de8:0x590ec6", text)
        self.assertNotIn("0x590ec9:0x590eda", text)
        self.assertNotIn("0x590ccb:0x590cf1", text)
        self.assertNotIn("0x590cf1:0x590dcb", text)
        self.assertNotIn("0x59c64f:0x59c2be", text)
        self.assertNotIn("0x590f92:0x5910eb", text)
        self.assertNotIn("0x594a91:0x594aa1", text)
        self.assertNotIn("0x594da8:0x594dc1", text)
        self.assertNotIn("0x594dc6:0x594dda", text)
        self.assertNotIn("0x72b3a8:0x72b3c6", text)
        self.assertNotIn('$wrapperJumpBypassSpecs += "0x72ad28:0x72ad46"', text)
        self.assertIn("DirectPatchSummary", text)
        self.assertIn("DirectPatchStartupHookOutput", text)
        self.assertIn("DirectPatchInlinePatchOffsets", text)
        self.assertIn("DirectPatchJumpBypassSpecs", text)
        self.assertIn("runescape-wrapper", text)
        self.assertIn("ClientLaunchBinaryKind", text)
        self.assertIn("BootstrapClientPid", text)
        self.assertIn("Resolve-MainClientProcess", text)
        self.assertIn("Convert-To947DirectClientLaunchArg", text)
        self.assertIn("Split-WindowsCommandLine", text)
        self.assertIn("Resolve-WrapperFallbackClientArgs", text)
        self.assertIn("Invoke-WrapperFallbackToDirectPatchedClient", text)
        self.assertIn("wrapper-child-override-mismatch", text)
        self.assertIn("$wrapperDonorCommandLine", text)
        self.assertIn("$wrapperFallbackClientArgs", text)
        self.assertIn("-FallbackClientArgs $wrapperFallbackClientArgs", text)
        self.assertIn("forcing direct patched fallback", text)
        self.assertIn("Wrapper child mismatch after requested override; forcing direct patched fallback", text)
        self.assertIn("$wrapperAcceptedInstalledRuntimeChild = $true", text)
        self.assertIn("Wrapper child stayed on synced installed runtime path; accepting child", text)
        self.assertNotIn("$postLaunchRuntimeCheck = $installedRuntimeSyncResult", text)
        self.assertIn('$normalizedLaunchArg = Convert-To947DirectClientLaunchArg -Url $LaunchArg', text)
        self.assertIn('@($normalizedLaunchArg)', text)
        self.assertIn('$launchArg = Convert-To947DirectClientLaunchArg -Url $launchArg', text)
        self.assertIn("WrapperFallbackToDirectPatched", text)
        self.assertIn('"runescape-wrapper"', text)
        self.assertIn("Direct rs2client patch launch completed but no live client process could be resolved.", text)
        self.assertIn("Refusing to launch an external client executable outside the workspace", text)
        self.assertIn("GpuPreferenceSummary", text)
        self.assertIn('-Preference "power-saving"', text)
        self.assertIn("Test-RecentD3DDeviceRemoved", text)
        self.assertIn("device was removed", text)
        self.assertIn('$effectiveGraphicsDevicePreference = "high-performance"', text)
        self.assertIn('$effectiveWindowsGpuPreference = "high-performance"', text)
        self.assertIn('"--client-arg={0}" -f $clientArg', text)

    def test_live_launcher_defaults_to_direct_patched_for_947(self) -> None:
        text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("launch_rs2client_direct_patch.py", text)
        self.assertIn("[switch]$UseRuneScapeWrapper", text)
        self.assertIn("$effectiveUseOriginalClient = $UseOriginalClient.IsPresent", text)
        self.assertNotIn("$effectiveUseOriginalClient = $UseOriginalClient.IsPresent -or (", text)
        self.assertNotIn("$useDirectPatchedOriginalPreview", text)
        self.assertIn("$selectedClientDir = if ($effectiveUseOriginalClient) { $originalClientDir } else { $clientDir }", text)
        self.assertIn("$selectedChildExe = Join-Path $selectedClientDir \"rs2client.exe\"", text)
        self.assertIn('if ($effectiveUseOriginalClient) { "original" } else { "patched" }', text)
        self.assertIn('PSBoundParameters.ContainsKey("DownloadMetadataSource")', text)
        self.assertIn("Get-QueryParameterValue", text)
        self.assertNotIn('Sync-InstalledRuneScapeRuntimeFile -SourcePath $installedGameClientExe -ClientDirectory $ClientDirectory -FileName "rs2client.exe"', text)
        self.assertIn("set_windows_gpu_preference.ps1", text)
        self.assertIn("sync_runescape_runtime_cache.ps1", text)
        self.assertIn("sync_runescape_installed_runtime.py", text)
        self.assertIn("$runtimePromoteToFullSync", text)
        self.assertIn("HotStubArchiveIdsBefore", text)
        self.assertIn("HotMissingReferenceTableArchiveIdsBefore", text)
        self.assertIn("CopiedHotArchiveIds", text)
        self.assertIn("$runtimeCopiedHotArchiveIds", text)
        self.assertIn("function Get-RuntimeArchiveSqliteShape", text)
        self.assertIn("$raw = $pythonScript | & $pythonCommand.Source - $Path 2>$null", text)
        self.assertIn("function Test-RuntimeArchiveHasMissingReferenceTable", text)
        self.assertIn("$runtimeUsesRetailStartupConfig = $configuredClientBuild -ge 947 -and $use947RetailConfigHost", text)
        self.assertIn("$runtimePromoteToFullSync = $runtimeUsesRetailStartupConfig -or ($prefer947PatchedDirectClient -and ($runtimeTargetArchiveCount.Count -lt $runtimeSourceFiles.Count -or $runtimeHotStubArchiveIds.Count -gt 0 -or $runtimeHotMissingReferenceTableArchiveIds.Count -gt 0))", text)
        self.assertIn("$runtimeMissingHotArchiveIds = @(", text)
        self.assertIn("$runtimeHotMissingReferenceTableArchiveIds = @()", text)
        self.assertIn("$runtimeHotMissingReferenceTableArchiveIds = @(", text)
        self.assertIn("$runtimeClientManagedHotArchiveSet = $configuredClientBuild -ge 947 -and $runtimeUsesRetailStartupConfig -and $prefer947PatchedDirectClient -and $runtimeMissingHotArchiveIds.Count -eq 0 -and $runtimeHotMissingReferenceTableArchiveIds.Count -eq 0", text)
        self.assertIn("$runtimeForceRetailRefreshHotArchiveSet = $false", text)
        self.assertIn("tearing down the runtime hot archive", text)
        self.assertIn("$runtimeShouldPreserveHotArchiveSet = (", text)
        self.assertIn("$runtimeForceRetailRefreshHotArchiveSet -or", text)
        self.assertIn('if ($runtimeShouldPreserveHotArchiveSet) {', text)
        self.assertIn('$runtimeCacheSyncParameters["SkipJs5Archives"] = $runtimeHotArchiveIds947', text)
        self.assertIn('if ((-not $runtimeClientManagedHotArchiveSet) -and (-not $runtimeForceRetailRefreshHotArchiveSet)) {', text)
        self.assertIn('$runtimeCacheSyncParameters["ValidateSkippedArchives"] = $true', text)
        self.assertIn('$runtimeShouldPreserveHotArchiveSet -and', text)
        self.assertIn('-not $runtimeClientManagedHotArchiveSet -and', text)
        self.assertIn('-not $runtimeForceRetailRefreshHotArchiveSet -and', text)
        self.assertIn('$runtimeHotStubArchiveIds.Count -gt 0', text)
        self.assertIn('$runtimeCacheSyncParameters["RescueSkippedBootstrapStubs"] = $true', text)
        self.assertIn("$runtimeHotStubArchiveIds = @()", text)
        self.assertIn("$runtimeShouldPreserveHotArchiveSet = $false", text)
        self.assertIn("$runtimeShouldAutoRepairHotCache947 = $configuredClientBuild -ge 947 -and (", text)
        self.assertIn('($runtimeForceRetailRefreshHotArchiveSet -and $runtimeShouldPreserveHotArchiveSet) -or', text)
        self.assertIn('($runtimeShouldPreserveHotArchiveSet -and -not $runtimeClientManagedHotArchiveSet -and ($runtimeHotStubArchiveIds.Count -gt 0 -or $runtimeHotMissingReferenceTableArchiveIds.Count -gt 0))', text)
        self.assertIn('"auto-hot-missing-reference-table-quarantine"', text)
        self.assertIn("$runtimeHotCacheRepairArchiveIds", text)
        self.assertIn("} elseif ($runtimeForceRetailRefreshHotArchiveSet) {", text)
        self.assertIn("@($runtimeHotArchiveIds947)", text)
        self.assertIn("} elseif ($runtimeShouldAutoRepairHotCache947) {", text)
        self.assertIn("@($runtimeHotStubArchiveIds) +", text)
        self.assertIn("@($runtimeHotMissingReferenceTableArchiveIds)", text)
        self.assertIn("($RepairRuntimeHotCache.IsPresent -or $runtimeShouldAutoRepairHotCache947) -and", text)
        self.assertNotIn("full-sync-copied-hot-archives", text)
        self.assertIn('hotMissingReferenceCount={7}', text)
        self.assertIn("RuntimeCacheSyncSummary", text)
        self.assertIn("RuntimeCacheSyncCopiedArchives", text)
        self.assertIn("RuntimeCacheSyncCopiedHotArchives", text)
        self.assertIn("RuntimeHotCacheRepairAutoTriggered", text)
        self.assertIn("RuntimeHotCacheRepairArchiveIds", text)
        self.assertIn("InstalledRuntimeSyncSummary", text)
        self.assertIn("InstalledRuntimeSyncLocalDir", text)
        self.assertIn("InstalledRuntimeSyncCopiedFiles", text)
        self.assertIn('"--timeout-seconds"', text)
        self.assertIn('"30"', text)
        self.assertIn('"--config-file"', text)
        self.assertIn('$startupConfigSnapshotReady = $false', text)
        self.assertIn('Remove-Item $startupConfigSnapshotPath -ErrorAction SilentlyContinue', text)
        self.assertIn("(Test-Path $startupConfigSnapshotPath)", text)
        self.assertIn('--rewrite-config-file', text)
        self.assertIn('$rewriteArgs += $startupConfigSnapshotPath', text)
        self.assertIn("Installed runtime sync completed but ProgramData runtime files still do not match the live manifest.", text)
        self.assertIn("$wrapperAcceptedInstalledRuntimeChild = $true", text)
        self.assertIn("wrapper child stayed on synced installed runtime path; accepting child", text)
        self.assertIn("$directPatchStartupHookOutput = Join-Path $root \"data\\\\debug\\\\direct-rs2client-patch\\\\latest-live-hook.jsonl\"", text)
        self.assertIn("--startup-hook-output", text)
        self.assertIn('"https://rs.config.runescape.com/k=5/l=0/jav_config.ws?binaryType=6&hostRewrite=0&lobbyHostRewrite=0&contentRouteRewrite=0&worldUrlRewrite=0&codebaseRewrite=0&gameHostRewrite=0&baseConfigSource=live&liveCache=1&downloadMetadataSource=original"', text)
        self.assertIn("Effective947StartupConfigHost", text)
        self.assertIn('gameHostRewrite=0', text)
        self.assertIn("$use947RetailConfigHost", text)
        self.assertIn("Sync-ContentHostsOverride", text)
        self.assertIn("[switch]$Force947StartupRouteRedirects", text)
        self.assertIn("--resolve-redirect", text)
        self.assertGreaterEqual(text.count("--resolve-redirect"), 2)
        self.assertNotIn('Where-Object { $_ -notin @("content.runescape.com", "rs.config.runescape.com") }', text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "contentRouteRewrite" -Value "1"', text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "gameHostRewrite" -Value "0"', text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "worldUrlRewrite" -Value "0"', text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "codebaseRewrite" -Value "0"', text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "gamePortOverride"', text)
        self.assertIn("Keep the default 947 wrapper route fully retail-shaped", text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "baseConfigSource"', text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "liveCache"', text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "baseConfigSnapshotPath"', text)
        self.assertIn("Get-947StartupConfigContent", text)
        self.assertIn("Get-947StartupParamMapFromConfigContent", text)
        self.assertIn("Convert-947StartupConfigToParamPairArgs", text)
        self.assertIn("Save-947StartupConfigSnapshot", text)
        self.assertIn("Get-947StartupRouteHostsFromConfigContent", text)
        self.assertIn("Get-947StartupWorldMitmHostsFromConfigContent", text)
        self.assertIn("Get-947StartupWorldMitmHosts", text)
        self.assertIn("$startupRouteHosts = @(Get-947StartupRouteHostsFromConfigContent -ConfigContent $startupConfigContent)", text)
        self.assertIn("(Get-947StartupWorldMitmHostsFromConfigContent -ConfigContent $startupConfigContent)", text)
        self.assertIn("Get-947SecureRetailWorldFleetHosts", text)
        self.assertIn('$startupLauncherToken947 = "A234"', text)
        self.assertIn('$paramPairArgs947 = @(Convert-947StartupConfigToParamPairArgs -ConfigContent $startupConfigContent -LauncherToken $startupLauncherToken947)', text)
        self.assertIn('$shouldUse947DirectParamPairArgs = $false', text)
        self.assertIn('if ($shouldUse947DirectParamPairArgs) {', text)
        self.assertIn('if ($configuredClientBuild -ge 947 -and [string]::IsNullOrWhiteSpace($startupConfigContent)) {', text)
        self.assertIn('[void]$arguments.Add("launcher")', text)
        self.assertIn("$startupRedirectHosts = @(", text)
        self.assertIn('(Get-947SecureRetailWorldFleetHosts)', text)
        self.assertIn('if ($configuredClientBuild -ge 947 -and $use947RetailConfigHost -and $script:UseContentTlsRoute) {', text)
        self.assertIn('if ($enable947StartupResolveRedirects) {', text)
        self.assertIn('function Test-947SecureStartupRedirectHost {', text)
        self.assertIn('Where-Object { $_ -notin @("localhost", "127.0.0.1", "::1", "rs.config.runescape.com") }', text)
        self.assertIn('Where-Object { Test-947SecureStartupRedirectHost -HostName $_ }', text)
        self.assertIn('($startupRedirectHosts | ForEach-Object { "{0}={1}" -f $_, $defaultMitmPrimaryHost })', text)
        self.assertNotIn('($startupRouteHosts | ForEach-Object { "{0}={1}" -f $_, $defaultMitmPrimaryHost })', text)
        self.assertIn('Write-LaunchTrace ("947 startup secure resolve redirects={0}" -f ($resolveRedirectSpecs -join ","))', text)
        self.assertIn('Write-LaunchTrace "947 startup secure resolve redirects=<disabled-default>"', text)
        self.assertIn("Get-947SecureRetailWorldFleetHosts", text)
        self.assertIn("$resolvedHost = Get-UriHostName -Value $candidateValue", text)
        self.assertNotIn("$host = Get-UriHostName -Value $candidateValue", text)
        self.assertIn('"-TlsExtraMitmHost"', text)
        self.assertIn('($extraTlsMitmHosts -join ",")', text)
        self.assertIn("tls_terminate_proxy.py", text)
        self.assertIn("CanonicalMitmTrustState", text)
        self.assertIn("started lobby proxy launcher pid=", text)
        self.assertIn('(\'"{0}"\' -f $lobbyProxyScript)', text)
        self.assertIn('if ($i -gt 0) {', text)
        self.assertIn('Wait-ListeningPorts', text)
        self.assertIn('wait-listening-ports query exception attempt={0} ports={1} message={2}', text)
        self.assertIn('ForEach-Object { [int]$_.LocalPort }', text)
        self.assertIn('-not ($listening -contains [int]$requiredPort)', text)
        self.assertIn('set "OPENNXT_ENABLE_RETAIL_RAW_CHECKSUM_PASSTHROUGH=1"', text)
        self.assertIn('set "OPENNXT_ENABLE_RETAIL_LOGGED_OUT_JS5_PASSTHROUGH=1"', text)
        self.assertNotIn('set "OPENNXT_ENABLE_LOGGED_OUT_JS5_PREFETCH_TABLE=1"', text)
        self.assertIn("$prefer947PatchedDirectClient = (", text)
        self.assertNotIn("-not $effectiveUseOriginalClient", text)
        self.assertIn("-and -not $prefer947PatchedDirectClient", text)
        self.assertIn("$useRuneScapeWrapperPreview = -not $prefer947PatchedDirectClient", text)
        self.assertIn("$useDirectPatchedPreview = $prefer947PatchedDirectClient", text)
        self.assertIn('"https://rs.config.runescape.com/k=5/l=0/jav_config.ws?binaryType=6&hostRewrite=0&lobbyHostRewrite=0&contentRouteRewrite=0&worldUrlRewrite=0&codebaseRewrite=0&gameHostRewrite=0"', text)
        self.assertIn("(($useRuneScapeWrapperPreview -or $useDirectPatchedPreview) -and $configuredClientBuild -ge 947)", text)
        self.assertIn("(($useRuneScapeWrapper -or $useDirectPatchedRs2Client) -and $configuredClientBuild -ge 947)", text)
        self.assertIn("if ($autoManageGraphicsCompat -and ($useRuneScapeWrapper -or $useDirectPatchedRs2Client) -and (Test-Path $launcherPreferencesScript))", text)
        self.assertIn("--patch-jump-bypass", text)
        self.assertIn("--patch-inline-offset", text)
        self.assertIn("--child-exe-override", text)
        self.assertIn("--accepted-child-exe", text)
        self.assertIn("--rewrite-scope", text)
        self.assertIn('"all"', text)
        self.assertIn("0x590001", text)
        self.assertIn('$directPatchInlinePatchOffsets += "0x590321"', text)
        self.assertIn("0x5916c3", text)
        self.assertIn("0x5916f0", text)
        self.assertIn("0x591712", text)
        self.assertIn("0x591719", text)
        self.assertIn("0x5919e3", text)
        self.assertIn("0x591a10", text)
        self.assertIn("0x591a32", text)
        self.assertIn("0x591a39", text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x590cf4"', text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x58ff0f"', text)
        self.assertIn("0x594d61", text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x59002d:0x5900a5"', text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x5902d5:0x5903bd"', text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x590c58:0x590c81"', text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x3699b2:0x3699f2"', text)
        self.assertIn('$directPatchJumpBypassSpecs += "0x7a3bc2:0x7a3bff"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59c1ea:0x59c21b"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59c2a0:0x59c64f"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590c72:0x590dba"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590de8:0x590ec6"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590ec9:0x590eda"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x58fa83:0x58fb29"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x5927f2:0x592826"', text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x5955a2"', text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x5953e4"', text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x596649"', text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x5967e5"', text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x597db1"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59707d:0x597087"', text)
        self.assertNotIn('$directPatchExtraArgs += "--producer-output-root"', text)
        self.assertNotIn('$directPatchExtraArgs += "--resource-gate-force-owner-stage-clear-when-drained"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59c64f:0x59c2be"', text)
        self.assertNotIn("0x594aaf:0x594aba", text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59034d:0x5903c6"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590f92:0x5910eb"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x594da8:0x594dc1"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x594dc6:0x594dda"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x72b3a8:0x72b3c6"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x72ad28:0x72ad46"', text)
        self.assertIn("-DirectPatchExtraArgs $directPatchExtraArgs `", text)
        self.assertIn("DirectPatchSummary", text)
        self.assertIn("DirectPatchStartupHookOutput", text)
        self.assertIn("DirectPatchInlinePatchOffsets", text)
        self.assertIn("DirectPatchJumpBypassSpecs", text)
        self.assertIn("ClientLaunchBinaryKind", text)
        self.assertIn("BootstrapClientPid", text)
        self.assertIn("Resolve-MainClientProcess", text)
        self.assertIn("Split-WindowsCommandLine", text)
        self.assertIn("Resolve-WrapperFallbackClientArgs", text)
        self.assertIn("Invoke-WrapperFallbackToDirectPatchedLive", text)
        self.assertIn("wrapper-child-override-mismatch", text)
        self.assertIn("$wrapperDonorCommandLine", text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("-DirectPatchExtraArgs $directPatchExtraArgs `", live_text)
        self.assertIn("$wrapperFallbackClientArgs", text)
        self.assertIn("-FallbackClientArgs $wrapperFallbackClientArgs", text)
        self.assertIn("wrapper child stayed on synced installed runtime path; accepting child", text)
        self.assertIn("WrapperFallbackToDirectPatched", text)
        self.assertIn("direct-patched-rs2client", text)
        self.assertIn('"runescape-wrapper"', text)
        self.assertIn("Direct rs2client patch launch completed but no live client process could be resolved.", text)
        self.assertIn("GpuPreferenceSummary", text)
        self.assertIn('-Preference "power-saving"', text)
        self.assertIn("Test-RecentD3DDeviceRemoved", text)
        self.assertIn("device was removed", text)
        self.assertIn('$effectiveGraphicsDevicePreference = "high-performance"', text)
        self.assertIn('$effectiveWindowsGpuPreference = "high-performance"', text)
        wrapper_text = (TOOLS_DIR / "launch_runescape_wrapper_rewrite.py").read_text(encoding="utf-8")
        self.assertIn('"overrideRequested": override_requested', wrapper_text)
        self.assertIn('"overrideApplied": override_applied', wrapper_text)
        self.assertIn('"overrideVerified": override_verified', wrapper_text)
        self.assertIn('"overrideAccepted": override_accepted', wrapper_text)
        self.assertIn('"acceptedChildExes": accepted_child_exes', wrapper_text)
        self.assertIn('"acceptedChildRefresh": accepted_child_refresh_state', wrapper_text)
        self.assertIn('"overrideMechanism": override_mechanism', wrapper_text)
        self.assertIn('"action": "accepted-child-exe-refresh-guard-armed"', wrapper_text)
        self.assertIn('"action": "accepted-child-exe-refreshed"', wrapper_text)
        self.assertIn('sendObservedProcessEvent("wrapper-child-createprocess-observed"', wrapper_text)
        self.assertIn('sendTrackedFileEvent("wrapper-file-create-observed"', wrapper_text)
        self.assertIn('sendTrackedFileEvent("wrapper-file-replace-observed"', wrapper_text)
        self.assertIn('"action": "child-exe-override-mismatch"', wrapper_text)
        self.assertIn('"action": "child-exe-override-accepted"', wrapper_text)
        self.assertIn("Requested child executable override was not applied.", wrapper_text)

    def test_bootstrap_stages_wrapper_into_local_client_directories(self) -> None:
        text = (TOOLS_DIR / "bootstrap_live_client_build.ps1").read_text(encoding="utf-8")
        self.assertIn("Games\\\\RuneScape\\\\RuneScape.exe", text)
        self.assertIn("Sync-InstalledRuneScapeWrapper", text)
        self.assertIn("Sync-InstalledRuneScapeRuntimeFile", text)
        self.assertNotIn('Sync-InstalledRuneScapeRuntimeFile -SourcePath $installedGameClientExe -ClientDirectory $directory -FileName "rs2client.exe"', text)
        self.assertIn("Win64cOriginalWrapper", text)
        self.assertIn("Win64cPatchedWrapper", text)
        self.assertIn("StagedWrapperPaths", text)

    def test_947_launchers_can_disable_legacy_inline_null_read_patches(self) -> None:
        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("[switch]$Disable947InlineNullReadPatches", client_text)
        self.assertIn("[switch]$Disable947InlineNullReadPatches", live_text)
        self.assertIn("if (-not $Disable947InlineNullReadPatches.IsPresent)", client_text)
        self.assertIn("if (-not $Disable947InlineNullReadPatches.IsPresent)", live_text)
        self.assertIn("Disable947InlineNullReadPatches", client_text)
        self.assertIn("Disable947InlineNullReadPatches", live_text)


if __name__ == "__main__":
    unittest.main()
