from __future__ import annotations

import re
import unittest
from pathlib import Path


TOOLS_DIR = Path(__file__).resolve().parent


class WrapperLaunchContractTest(unittest.TestCase):
    def test_direct_patch_launchers_use_summary_handshake(self) -> None:
        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn('$directPatchStdout = Join-Path $root "data\\\\debug\\\\direct-rs2client-patch\\\\latest-live.stdout.log"', live_text)
        self.assertIn('$directPatchStderr = Join-Path $root "data\\\\debug\\\\direct-rs2client-patch\\\\latest-live.stderr.log"', live_text)
        self.assertIn('$directPatchHelper = Start-Process `', live_text)
        self.assertIn('-RedirectStandardOutput $directPatchStdout `', live_text)
        self.assertIn('-RedirectStandardError $directPatchStderr `', live_text)
        self.assertIn('Write-LaunchTrace ("direct patch helper start exe={0}" -f $ClientExePath)', live_text)
        self.assertIn('Write-LaunchTrace ("direct patch helper summary ready helperPid={0}" -f $directPatchHelper.Id)', live_text)
        self.assertIn('Write-LaunchTrace ("direct patch helper summary loaded helperPid={0} pid={1} stage={2}" -f $directPatchHelper.Id, $directPatchLaunchSummary.pid, $summaryStage)', live_text)
        self.assertIn('Write-LaunchTrace ("direct patch helper client resolved helperPid={0} pid={1}" -f $directPatchHelper.Id, $client.Id)', live_text)
        self.assertIn('Write-LaunchTrace ("launch state written file={0}" -f $launchStateFile)', live_text)

        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn('$directPatchStdout = Join-Path $root "data\\\\debug\\\\direct-rs2client-patch\\\\latest-client-only.stdout.log"', client_text)
        self.assertIn('$directPatchStderr = Join-Path $root "data\\\\debug\\\\direct-rs2client-patch\\\\latest-client-only.stderr.log"', client_text)
        self.assertIn('$helperProcess = Start-Process `', client_text)
        self.assertIn('-RedirectStandardOutput $directPatchStdout `', client_text)
        self.assertIn('-RedirectStandardError $directPatchStderr `', client_text)
        self.assertIn('Direct patch launch retrying without pre-resume Frida startup hook or startup redirects', client_text)

    def test_direct_947_startup_contract_stays_retail_shaped(self) -> None:
        client_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn("Keep the direct 947 startup contract retail-shaped", client_text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "gamePortOverride"', client_text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "contentRouteRewrite" -Value "0"', client_text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "worldUrlRewrite" -Value "0"', client_text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "codebaseRewrite" -Value "0"', client_text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "baseConfigSnapshotPath"', client_text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("Keep the visible 947 direct startup contract retail-shaped", live_text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "gamePortOverride"', live_text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "contentRouteRewrite" -Value "0"', live_text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "worldUrlRewrite" -Value "0"', live_text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "codebaseRewrite" -Value "0"', live_text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "baseConfigSnapshotPath"', live_text)

    def test_direct_947_launch_arg_restores_local_bridge_contract(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        match = re.search(
            r"function Convert-To947DirectClientLaunchArg \{(?P<body>.*?)^\}",
            text,
            re.MULTILINE | re.DOTALL,
        )
        self.assertIsNotNone(match)
        body = match.group("body")
        self.assertIn('Set-QueryParameter -Url $Url -Name "contentRouteRewrite" -Value "1"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "worldUrlRewrite" -Value "1"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "codebaseRewrite" -Value "1"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "baseConfigSource" -Value "live"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "liveCache" -Value "1"', body)
        self.assertIn('Set-QueryParameter -Url $updated -Name "gamePortOverride" -Value $GamePort', body)
        self.assertNotIn('Remove-QueryParameter -Url $updated -Name "baseConfigSource"', body)
        self.assertNotIn('Remove-QueryParameter -Url $updated -Name "liveCache"', body)

    def test_explicit_947_config_urls_are_not_silently_rewritten_back_to_retail(self) -> None:
        client_only_text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn('$configUrlExplicit = $PSBoundParameters.ContainsKey("ConfigUrl") -and -not [string]::IsNullOrWhiteSpace($ConfigUrl)', client_only_text)
        self.assertIn("respect an explicit caller-provided startup contract", client_only_text)
        self.assertIn("if (-not $configUrlExplicit) {", client_only_text)

        live_text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn('$configUrlOverrideExplicit = $PSBoundParameters.ContainsKey("ConfigUrlOverride") -and -not [string]::IsNullOrWhiteSpace($ConfigUrlOverride)', live_text)
        self.assertIn("preserve an explicit ConfigUrlOverride", live_text)
        self.assertIn("if (-not $configUrlOverrideExplicit) {", live_text)

    def test_client_only_launcher_defaults_to_direct_patched_for_947(self) -> None:
        text = (TOOLS_DIR / "launch-client-only.ps1").read_text(encoding="utf-8")
        self.assertIn("launch_runescape_wrapper_rewrite.py", text)
        self.assertIn("[switch]$UseRuneScapeWrapper", text)
        self.assertNotIn('Sync-InstalledRuneScapeRuntimeFile -SourcePath $installedGameClientExe -ClientDirectory $ClientDirectory -FileName "rs2client.exe"', text)
        self.assertIn("$prefer947OriginalClientFamily", text)
        self.assertIn('[string]::Equals($effectiveClientVariant, "original", [System.StringComparison]::OrdinalIgnoreCase)', text)
        self.assertIn("AutoSelectedOriginalClient = $false", text)
        self.assertIn("$selectedRuneScapeWrapper = Join-Path $clientDir \"RuneScape.exe\"", text)
        self.assertIn("$localChildExe = Join-Path $clientDir \"rs2client.exe\"", text)
        self.assertIn("$explicitClientExeOverride = -not [string]::IsNullOrWhiteSpace($ClientExeOverride)", text)
        self.assertIn("Sync-InstalledRuneScapeWrapper -ClientDirectory $clientDir", text)
        self.assertIn("$prefer947PatchedDirectClient", text)
        self.assertIn("-and -not $prefer947PatchedDirectClient", text)
        self.assertNotIn('-not [string]::Equals($effectiveClientVariant, "original"', text)
        self.assertIn("$existingDownloadMetadataSource = Get-QueryParameterValue -Url $ConfigUrl -Name \"downloadMetadataSource\"", text)
        self.assertIn("Remove-QueryParameter", text)
        self.assertIn("$effectiveClientVariant.Trim().ToLowerInvariant()", text)
        self.assertIn('ClientVariant = "patched"', text)
        self.assertIn("$useDirectPatchedRs2Client", text)
        self.assertIn("(($launchViaRuneScapeWrapper -or $useDirectPatchedRs2Client) -and $configuredClientBuild -ge 947)", text)
        self.assertIn("if ($autoManageGraphicsCompat -and ($launchViaRuneScapeWrapper -or $useDirectPatchedRs2Client) -and (Test-Path $launcherPreferencesScript))", text)
        self.assertIn("$directPatchStartupHookOutput = Join-Path $root \"data\\\\debug\\\\direct-rs2client-patch\\\\latest-client-only-hook.jsonl\"", text)
        self.assertIn("--startup-hook-output", text)
        self.assertIn('"https://rs.config.runescape.com/k=5/l=0/jav_config.ws?binaryType=6&hostRewrite=0&lobbyHostRewrite=0&contentRouteRewrite=0&worldUrlRewrite=0&codebaseRewrite=0&gameHostRewrite=0"', text)
        self.assertIn("Convert-ToLoopbackJavConfigUrl", text)
        self.assertIn('gameHostRewrite=0', text)
        self.assertIn("keep the 947 wrapper startup contract", text)
        self.assertIn('Set-QueryParameter -Url $launchArg -Name "codebaseRewrite" -Value "0"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "contentRouteRewrite" -Value "1"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "worldUrlRewrite" -Value "1"', text)
        self.assertIn('$use947RetailConfigRoute = $ConfigUrl -like "https://rs.config.runescape.com*"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "codebaseRewrite" -Value "1"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "codebaseRewrite" -Value "1"', text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "gamePortOverride"', text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "baseConfigSource"', text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "liveCache"', text)
        self.assertIn('Remove-QueryParameter -Url $ConfigUrl -Name "baseConfigSnapshotPath"', text)
        self.assertIn("Get-947StartupConfigContent", text)
        self.assertIn("Get-947StartupParamMapFromConfigContent", text)
        self.assertIn("Convert-947StartupConfigToParamPairArgs", text)
        self.assertIn("Save-947StartupConfigSnapshot", text)
        self.assertIn("Get-947StartupRouteHostsFromConfigContent", text)
        self.assertIn("Get-947StartupWorldMitmHostsFromConfigContent", text)
        self.assertIn('$startupLauncherToken947 = "A234"', text)
        self.assertIn('$paramPairArgs947 = @(Convert-947StartupConfigToParamPairArgs -ConfigContent $startupConfigContent -LauncherToken $startupLauncherToken947)', text)
        self.assertIn('$shouldUse947DirectParamPairArgs = $false', text)
        self.assertIn('if ($shouldUse947DirectParamPairArgs) {', text)
        self.assertIn('$use947DirectParamPairArgs = $false', text)
        self.assertIn('} elseif ($effectiveUseConfigUriArg -and -not $use947DirectParamPairArgs) {', text)
        self.assertIn('[void]$arguments.Add("launcher")', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "gameHostRewrite" -Value "0"', text)
        self.assertIn("--rsa-config", text)
        self.assertIn("set_windows_gpu_preference.ps1", text)
        self.assertIn("sync_runescape_runtime_cache.ps1", text)
        self.assertIn("sync_runescape_installed_runtime.py", text)
        self.assertIn("$runtimePromoteToFullSync", text)
        self.assertIn("HotStubArchiveIdsBefore", text)
        self.assertIn("CopiedHotArchiveIds", text)
        self.assertIn("$runtimeCopiedHotArchiveIds", text)
        self.assertIn("$runtimeUsesRetailStartupConfig = $configuredClientBuild -ge 947 -and $use947RetailConfigRoute", text)
        self.assertIn("$runtimePromoteToFullSync = $runtimeUsesRetailStartupConfig -or ($useDirectPatchedRs2Client -and ($runtimeTargetFiles.Count -lt $runtimeSourceFiles.Count -or $runtimeHotStubArchiveIds.Count -gt 0))", text)
        self.assertIn("$runtimeMissingHotArchiveIds = @(", text)
        self.assertIn("$runtimeClientManagedHotArchiveSet = $configuredClientBuild -ge 947 -and $runtimeUsesRetailStartupConfig -and $useDirectPatchedRs2Client -and $runtimeMissingHotArchiveIds.Count -eq 0", text)
        self.assertIn("$runtimeShouldPreserveHotArchiveSet = $runtimeClientManagedHotArchiveSet -or ((-not $useDirectPatchedRs2Client) -and (-not $runtimeUsesRetailStartupConfig) -and -not $RepairRuntimeHotCache.IsPresent)", text)
        self.assertIn('if ($runtimeShouldPreserveHotArchiveSet) {', text)
        self.assertIn('$runtimeCacheSyncParameters["SkipJs5Archives"] = $runtimeHotArchiveIds947', text)
        self.assertIn('if (-not $runtimeClientManagedHotArchiveSet) {', text)
        self.assertIn('$runtimeCacheSyncParameters["ValidateSkippedArchives"] = $true', text)
        self.assertIn('if ($runtimeShouldPreserveHotArchiveSet -and -not $runtimeClientManagedHotArchiveSet -and $runtimeHotStubArchiveIds.Count -gt 0) {', text)
        self.assertIn('$runtimeCacheSyncParameters["RescueSkippedBootstrapStubs"] = $true', text)
        self.assertIn("$runtimeHotStubArchiveIds = @()", text)
        self.assertIn("$runtimeShouldPreserveHotArchiveSet = $false", text)
        self.assertIn("$runtimeShouldAutoRepairHotCache947 = $configuredClientBuild -ge 947 -and $runtimeShouldPreserveHotArchiveSet -and -not $runtimeClientManagedHotArchiveSet -and $runtimeHotStubArchiveIds.Count -gt 0", text)
        self.assertIn('$runtimeAutoRepairReason = "auto-hot-stub-quarantine"', text)
        self.assertIn("$runtimeHotCacheRepairArchiveIds", text)
        self.assertIn("-IncludeAuxiliaryFiles", text)
        self.assertIn("} elseif ($runtimeShouldAutoRepairHotCache947) {", text)
        self.assertIn("@($runtimeHotStubArchiveIds)", text)
        self.assertIn("($RepairRuntimeHotCache.IsPresent -or $runtimeShouldAutoRepairHotCache947) -and", text)
        self.assertNotIn("full-sync-copied-hot-archives", text)
        self.assertIn('$runtimeSyncMode = if ($runtimePromoteToFullSync) { "full" } else { "seed-missing" }', text)
        self.assertIn('SyncMode -NotePropertyValue $runtimeSyncMode', text)
        self.assertIn("$runtimeSyncLocalDir = $clientDir", text)
        self.assertIn('@(\"original\", \"patched\", \"compressed\") -contains $resolvedDownloadMetadataSource', text)
        self.assertIn('PSBoundParameters.ContainsKey("DownloadMetadataSource")', text)
        self.assertIn("Get-QueryParameterValue", text)
        self.assertIn("Remove-QueryParameter", text)
        self.assertIn("RuntimeCacheSyncSummary", text)
        self.assertIn("RuntimeCacheSyncCopiedArchives", text)
        self.assertIn("RuntimeCacheSyncCopiedHotArchives", text)
        self.assertIn("RuntimeHotCacheRepairAutoTriggered", text)
        self.assertIn("RuntimeHotCacheRepairArchiveIds", text)
        self.assertIn("Sync-RetailHostsOverride", text)
        self.assertIn("Test-HostsFileWriteAccess", text)
        self.assertIn("$script:ConfiguredTlsExtraMitmHosts = @()", text)
        self.assertIn("$script:ConfiguredTlsExtraMitmHosts", text)
        self.assertIn("$startupRouteHosts = @()", text)
        self.assertIn('if ($configuredClientBuild -ge 947 -and $use947RetailConfigRoute -and -not $useDirectPatchedRs2Client -and -not $script:CanWriteHostsFile) {', text)
        self.assertIn('Get-947StartupRouteHostsFromConfigContent -ConfigContent $startupConfigContent', text)
        self.assertIn("$startupRedirectHosts = @(", text)
        self.assertIn('Get-947StartupWorldMitmHostsFromConfigContent -ConfigContent $startupConfigContent', text)
        self.assertIn('@("localhost", "127.0.0.1", "::1", "content.runescape.com", "rs.config.runescape.com")', text)
        self.assertIn('($startupRedirectHosts | ForEach-Object { "{0}={1}" -f $_, $defaultMitmPrimaryHost })', text)
        self.assertIn("--resolve-redirect", text)
        self.assertGreaterEqual(text.count("--resolve-redirect"), 2)
        self.assertNotIn('Where-Object { $_ -notin @("rs.config.runescape.com") }', text)
        self.assertNotIn('"rs.config.runescape.com=localhost"', text)
        self.assertNotIn('($startupRouteHosts | ForEach-Object { "{0}={1}" -f $_, $defaultMitmPrimaryHost })', text)
        self.assertIn("InstalledRuntimeSyncSummary", text)
        self.assertIn("InstalledRuntimeSyncLocalDir", text)
        self.assertIn("InstalledRuntimeSyncCopiedFiles", text)
        self.assertIn("InstalledRuntimeSyncInstalledReadyAfter", text)
        self.assertIn("InstalledRuntimeSyncFailedFiles", text)
        self.assertIn('"--timeout-seconds"', text)
        self.assertIn('"30"', text)
        self.assertIn('"--config-file"', text)
        self.assertIn("(Test-Path $startupConfigSnapshotPath)", text)
        self.assertIn("ProgramData runtime files still do not match the live manifest.", text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "worldUrlRewrite" -Value "1"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "baseConfigSource" -Value "live"', text)
        self.assertIn('Set-QueryParameter -Url $ConfigUrl -Name "liveCache" -Value "1"', text)
        self.assertIn("--patch-jump-bypass", text)
        self.assertIn("--patch-inline-offset", text)
        self.assertIn("--child-exe-override", text)
        self.assertIn("--rewrite-scope", text)
        self.assertIn('"all"', text)
        self.assertIn("0x590001", text)
        self.assertIn("0x590321", text)
        self.assertIn("0x5916c3", text)
        self.assertIn("0x5916f0", text)
        self.assertIn("0x591712", text)
        self.assertIn("0x591719", text)
        self.assertIn("0x5919e3", text)
        self.assertIn("0x591a10", text)
        self.assertIn("0x591a32", text)
        self.assertIn("0x591a39", text)
        self.assertIn("0x594a41", text)
        self.assertIn("0x594d61", text)
        self.assertIn("0x59002d:0x5900a5", text)
        self.assertIn("0x59034d:0x5903c5", text)
        self.assertIn("0x590c72:0x590dcb", text)
        self.assertIn("0x590f92:0x5910eb", text)
        self.assertIn("0x594a91:0x594aa1", text)
        self.assertIn("0x72b3a8:0x72b3c6", text)
        self.assertIn("0x72ad28:0x72ad46", text)
        self.assertIn("DirectPatchSummary", text)
        self.assertIn("DirectPatchStartupHookOutput", text)
        self.assertIn("DirectPatchInlinePatchOffsets", text)
        self.assertIn("DirectPatchJumpBypassSpecs", text)
        self.assertIn("runescape-wrapper", text)
        self.assertIn("ClientLaunchBinaryKind", text)
        self.assertIn("BootstrapClientPid", text)
        self.assertIn("Resolve-MainClientProcess", text)
        self.assertIn("Convert-To947DirectClientLaunchArg", text)
        self.assertIn("Split-WindowsCommandLine", text)
        self.assertIn("Resolve-WrapperFallbackClientArgs", text)
        self.assertIn("Invoke-WrapperFallbackToDirectPatchedClient", text)
        self.assertIn("wrapper-child-override-mismatch", text)
        self.assertIn("$wrapperDonorCommandLine", text)
        self.assertIn("$wrapperFallbackClientArgs", text)
        self.assertIn("-FallbackClientArgs $wrapperFallbackClientArgs", text)
        self.assertIn("forcing direct patched fallback", text)
        self.assertIn("Wrapper child mismatch after requested override; forcing direct patched fallback", text)
        self.assertIn("$wrapperAcceptedInstalledRuntimeChild = $true", text)
        self.assertIn("Wrapper child stayed on synced installed runtime path; accepting child", text)
        self.assertNotIn("$postLaunchRuntimeCheck = $installedRuntimeSyncResult", text)
        self.assertIn('$normalizedLaunchArg = Convert-To947DirectClientLaunchArg -Url $LaunchArg', text)
        self.assertIn('@($normalizedLaunchArg)', text)
        self.assertIn('$launchArg = Convert-To947DirectClientLaunchArg -Url $launchArg', text)
        self.assertIn("WrapperFallbackToDirectPatched", text)
        self.assertIn('"runescape-wrapper"', text)
        self.assertIn("Direct rs2client patch launch completed but no live client process could be resolved.", text)
        self.assertIn("Refusing to launch an external client executable outside the workspace", text)
        self.assertIn("GpuPreferenceSummary", text)
        self.assertIn('-Preference "high-performance"', text)
        self.assertIn('"--client-arg={0}" -f $clientArg', text)

    def test_live_launcher_defaults_to_direct_patched_for_947(self) -> None:
        text = (TOOLS_DIR / "launch-win64c-live.ps1").read_text(encoding="utf-8")
        self.assertIn("launch_rs2client_direct_patch.py", text)
        self.assertIn("[switch]$UseRuneScapeWrapper", text)
        self.assertIn("$effectiveUseOriginalClient = $UseOriginalClient.IsPresent", text)
        self.assertNotIn("$effectiveUseOriginalClient = $UseOriginalClient.IsPresent -or (", text)
        self.assertNotIn("$useDirectPatchedOriginalPreview", text)
        self.assertIn("$selectedClientDir = if ($effectiveUseOriginalClient) { $originalClientDir } else { $clientDir }", text)
        self.assertIn("$selectedChildExe = Join-Path $selectedClientDir \"rs2client.exe\"", text)
        self.assertIn('if ($effectiveUseOriginalClient) { "original" } else { "patched" }', text)
        self.assertIn('PSBoundParameters.ContainsKey("DownloadMetadataSource")', text)
        self.assertIn("Get-QueryParameterValue", text)
        self.assertNotIn('Sync-InstalledRuneScapeRuntimeFile -SourcePath $installedGameClientExe -ClientDirectory $ClientDirectory -FileName "rs2client.exe"', text)
        self.assertIn("set_windows_gpu_preference.ps1", text)
        self.assertIn("sync_runescape_runtime_cache.ps1", text)
        self.assertIn("sync_runescape_installed_runtime.py", text)
        self.assertIn("$runtimePromoteToFullSync", text)
        self.assertIn("HotStubArchiveIdsBefore", text)
        self.assertIn("CopiedHotArchiveIds", text)
        self.assertIn("$runtimeCopiedHotArchiveIds", text)
        self.assertIn("$runtimeUsesRetailStartupConfig = $configuredClientBuild -ge 947 -and $use947RetailConfigHost", text)
        self.assertIn("$runtimePromoteToFullSync = $runtimeUsesRetailStartupConfig -or ($prefer947PatchedDirectClient -and ($runtimeTargetFiles.Count -lt $runtimeSourceFiles.Count -or $runtimeHotStubArchiveIds.Count -gt 0))", text)
        self.assertIn("$runtimeMissingHotArchiveIds = @(", text)
        self.assertIn("$runtimeClientManagedHotArchiveSet = $configuredClientBuild -ge 947 -and $runtimeUsesRetailStartupConfig -and $prefer947PatchedDirectClient -and $runtimeMissingHotArchiveIds.Count -eq 0", text)
        self.assertIn("$runtimeShouldPreserveHotArchiveSet = $runtimeClientManagedHotArchiveSet -or ((-not $prefer947PatchedDirectClient) -and (-not $runtimeUsesRetailStartupConfig) -and -not $RepairRuntimeHotCache.IsPresent)", text)
        self.assertIn('if ($runtimeShouldPreserveHotArchiveSet) {', text)
        self.assertIn('$runtimeCacheSyncParameters["SkipJs5Archives"] = $runtimeHotArchiveIds947', text)
        self.assertIn('if (-not $runtimeClientManagedHotArchiveSet) {', text)
        self.assertIn('$runtimeCacheSyncParameters["ValidateSkippedArchives"] = $true', text)
        self.assertIn('if ($runtimeShouldPreserveHotArchiveSet -and -not $runtimeClientManagedHotArchiveSet -and $runtimeHotStubArchiveIds.Count -gt 0) {', text)
        self.assertIn('$runtimeCacheSyncParameters["RescueSkippedBootstrapStubs"] = $true', text)
        self.assertIn("$runtimeHotStubArchiveIds = @()", text)
        self.assertIn("$runtimeShouldPreserveHotArchiveSet = $false", text)
        self.assertIn("$runtimeShouldAutoRepairHotCache947 = $configuredClientBuild -ge 947 -and $runtimeShouldPreserveHotArchiveSet -and -not $runtimeClientManagedHotArchiveSet -and $runtimeHotStubArchiveIds.Count -gt 0", text)
        self.assertIn('$runtimeAutoRepairReason = "auto-hot-stub-quarantine"', text)
        self.assertIn("$runtimeHotCacheRepairArchiveIds", text)
        self.assertIn("-IncludeAuxiliaryFiles", text)
        self.assertIn("} elseif ($runtimeShouldAutoRepairHotCache947) {", text)
        self.assertIn("@($runtimeHotStubArchiveIds)", text)
        self.assertIn("($RepairRuntimeHotCache.IsPresent -or $runtimeShouldAutoRepairHotCache947) -and", text)
        self.assertNotIn("full-sync-copied-hot-archives", text)
        self.assertIn('runtime cache sync mode={0}', text)
        self.assertIn("RuntimeCacheSyncSummary", text)
        self.assertIn("RuntimeCacheSyncCopiedArchives", text)
        self.assertIn("RuntimeCacheSyncCopiedHotArchives", text)
        self.assertIn("RuntimeHotCacheRepairAutoTriggered", text)
        self.assertIn("RuntimeHotCacheRepairArchiveIds", text)
        self.assertIn("InstalledRuntimeSyncSummary", text)
        self.assertIn("InstalledRuntimeSyncLocalDir", text)
        self.assertIn("InstalledRuntimeSyncCopiedFiles", text)
        self.assertIn('"--timeout-seconds"', text)
        self.assertIn('"30"', text)
        self.assertIn('"--config-file"', text)
        self.assertIn("(Test-Path $startupConfigSnapshotPath)", text)
        self.assertIn("Installed runtime sync completed but ProgramData runtime files still do not match the live manifest.", text)
        self.assertIn("$wrapperAcceptedInstalledRuntimeChild = $true", text)
        self.assertIn("wrapper child stayed on synced installed runtime path; accepting child", text)
        self.assertIn("$directPatchStartupHookOutput = Join-Path $root \"data\\\\debug\\\\direct-rs2client-patch\\\\latest-live-hook.jsonl\"", text)
        self.assertIn("--startup-hook-output", text)
        self.assertIn('"https://rs.config.runescape.com/k=5/l=0/jav_config.ws?binaryType=6&hostRewrite=0&lobbyHostRewrite=0&contentRouteRewrite=0&worldUrlRewrite=0&codebaseRewrite=0&gameHostRewrite=0"', text)
        self.assertIn("Effective947StartupConfigHost", text)
        self.assertIn('gameHostRewrite=0', text)
        self.assertIn("$use947RetailConfigHost", text)
        self.assertIn("Sync-ContentHostsOverride", text)
        self.assertIn("--resolve-redirect", text)
        self.assertGreaterEqual(text.count("--resolve-redirect"), 2)
        self.assertNotIn('Where-Object { $_ -notin @("content.runescape.com", "rs.config.runescape.com") }', text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "contentRouteRewrite" -Value "1"', text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "gameHostRewrite" -Value "0"', text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "worldUrlRewrite" -Value "0"', text)
        self.assertIn('Set-QueryParameter -Url $effectiveLaunchArg -Name "codebaseRewrite" -Value "0"', text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "gamePortOverride"', text)
        self.assertIn("Keep the default 947 wrapper route fully retail-shaped", text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "baseConfigSource"', text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "liveCache"', text)
        self.assertIn('Remove-QueryParameter -Url $effectiveLaunchArg -Name "baseConfigSnapshotPath"', text)
        self.assertIn("Get-947StartupConfigContent", text)
        self.assertIn("Get-947StartupParamMapFromConfigContent", text)
        self.assertIn("Convert-947StartupConfigToParamPairArgs", text)
        self.assertIn("Save-947StartupConfigSnapshot", text)
        self.assertIn("Get-947StartupRouteHostsFromConfigContent", text)
        self.assertIn("Get-947StartupWorldMitmHostsFromConfigContent", text)
        self.assertIn("Get-947StartupWorldMitmHosts", text)
        self.assertIn("$startupRouteHosts = @(Get-947StartupRouteHostsFromConfigContent -ConfigContent $startupConfigContent)", text)
        self.assertIn('$startupLauncherToken947 = "A234"', text)
        self.assertIn('$paramPairArgs947 = @(Convert-947StartupConfigToParamPairArgs -ConfigContent $startupConfigContent -LauncherToken $startupLauncherToken947)', text)
        self.assertIn('$shouldUse947DirectParamPairArgs = $false', text)
        self.assertIn('if ($shouldUse947DirectParamPairArgs) {', text)
        self.assertIn('if ($configuredClientBuild -ge 947 -and [string]::IsNullOrWhiteSpace($startupConfigContent)) {', text)
        self.assertIn('[void]$arguments.Add("launcher")', text)
        self.assertIn("$startupRedirectHosts = @(", text)
        self.assertIn('if ($configuredClientBuild -ge 947 -and $use947RetailConfigHost -and -not $prefer947PatchedDirectClient -and $script:UseContentTlsRoute -and -not $script:CanWriteHostsFile) {', text)
        self.assertIn('Get-947StartupWorldMitmHostsFromConfigContent -ConfigContent $startupConfigContent', text)
        self.assertIn('if ($uriHost -in @("localhost", "127.0.0.1", "::1", "content.runescape.com", "rs.config.runescape.com")) {', text)
        self.assertIn('($startupRedirectHosts | ForEach-Object { "{0}={1}" -f $_, $defaultMitmPrimaryHost })', text)
        self.assertNotIn('($startupRouteHosts | ForEach-Object { "{0}={1}" -f $_, $defaultMitmPrimaryHost })', text)
        self.assertIn('Write-LaunchTrace ("947 startup secure resolve redirects={0}" -f ($resolveRedirectSpecs -join ","))', text)
        self.assertIn("$resolvedHost = Get-UriHostName -Value $candidateValue", text)
        self.assertNotIn("$host = Get-UriHostName -Value $candidateValue", text)
        self.assertIn('"-TlsExtraMitmHost"', text)
        self.assertIn("tls_terminate_proxy.py", text)
        self.assertIn("CanonicalMitmTrustState", text)
        self.assertIn("started lobby proxy launcher pid=", text)
        self.assertIn('(\'"{0}"\' -f $lobbyProxyScript)', text)
        self.assertIn("$prefer947PatchedDirectClient = (", text)
        self.assertNotIn("-not $effectiveUseOriginalClient", text)
        self.assertIn("-and -not $prefer947PatchedDirectClient", text)
        self.assertIn("$useRuneScapeWrapperPreview = -not $prefer947PatchedDirectClient", text)
        self.assertIn("$useDirectPatchedPreview = $prefer947PatchedDirectClient", text)
        self.assertIn('"https://rs.config.runescape.com/k=5/l=0/jav_config.ws?binaryType=6&hostRewrite=0&lobbyHostRewrite=0&contentRouteRewrite=0&worldUrlRewrite=0&codebaseRewrite=0&gameHostRewrite=0"', text)
        self.assertIn("(($useRuneScapeWrapperPreview -or $useDirectPatchedPreview) -and $configuredClientBuild -ge 947)", text)
        self.assertIn("(($useRuneScapeWrapper -or $useDirectPatchedRs2Client) -and $configuredClientBuild -ge 947)", text)
        self.assertIn("if ($autoManageGraphicsCompat -and ($useRuneScapeWrapper -or $useDirectPatchedRs2Client) -and (Test-Path $launcherPreferencesScript))", text)
        self.assertIn("--patch-jump-bypass", text)
        self.assertIn("--patch-inline-offset", text)
        self.assertIn("--child-exe-override", text)
        self.assertIn("--rewrite-scope", text)
        self.assertIn('"all"', text)
        self.assertIn("0x590001", text)
        self.assertNotIn('$directPatchInlinePatchOffsets += "0x590321"', text)
        self.assertIn("0x5916c3", text)
        self.assertIn("0x5916f0", text)
        self.assertIn("0x591712", text)
        self.assertIn("0x591719", text)
        self.assertIn("0x5919e3", text)
        self.assertIn("0x591a10", text)
        self.assertIn("0x591a32", text)
        self.assertIn("0x591a39", text)
        self.assertIn("0x594d61", text)
        self.assertIn("0x59002d:0x5900a5", text)
        self.assertIn("0x590c72:0x590dcb", text)
        self.assertIn("0x594aaf:0x594aba", text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x59034d:0x5903c5"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x590f92:0x5910eb"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x594da8:0x594dc1"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x594dc6:0x594dda"', text)
        self.assertNotIn('$directPatchJumpBypassSpecs += "0x72b3a8:0x72b3c6"', text)
        self.assertIn("0x72ad28:0x72ad46", text)
        self.assertIn("DirectPatchSummary", text)
        self.assertIn("DirectPatchStartupHookOutput", text)
        self.assertIn("DirectPatchInlinePatchOffsets", text)
        self.assertIn("DirectPatchJumpBypassSpecs", text)
        self.assertIn("ClientLaunchBinaryKind", text)
        self.assertIn("BootstrapClientPid", text)
        self.assertIn("Resolve-MainClientProcess", text)
        self.assertIn("Split-WindowsCommandLine", text)
        self.assertIn("Resolve-WrapperFallbackClientArgs", text)
        self.assertIn("Invoke-WrapperFallbackToDirectPatchedLive", text)
        self.assertIn("wrapper-child-override-mismatch", text)
        self.assertIn("$wrapperDonorCommandLine", text)
        self.assertIn("$wrapperFallbackClientArgs", text)
        self.assertIn("-FallbackClientArgs $wrapperFallbackClientArgs", text)
        self.assertIn("wrapper child stayed on synced installed runtime path; accepting child", text)
        self.assertIn("WrapperFallbackToDirectPatched", text)
        self.assertIn("direct-patched-rs2client", text)
        self.assertIn('"runescape-wrapper"', text)
        self.assertIn("Direct rs2client patch launch completed but no live client process could be resolved.", text)
        self.assertIn("GpuPreferenceSummary", text)
        self.assertIn('-Preference "high-performance"', text)
        wrapper_text = (TOOLS_DIR / "launch_runescape_wrapper_rewrite.py").read_text(encoding="utf-8")
        self.assertIn('"overrideRequested": override_requested', wrapper_text)
        self.assertIn('"overrideApplied": override_applied', wrapper_text)
        self.assertIn('"overrideVerified": override_verified', wrapper_text)
        self.assertIn('"overrideMechanism": override_mechanism', wrapper_text)
        self.assertIn('"action": "child-exe-override-mismatch"', wrapper_text)
        self.assertIn("Requested child executable override was not applied.", wrapper_text)

    def test_bootstrap_stages_wrapper_into_local_client_directories(self) -> None:
        text = (TOOLS_DIR / "bootstrap_live_client_build.ps1").read_text(encoding="utf-8")
        self.assertIn("Games\\\\RuneScape\\\\RuneScape.exe", text)
        self.assertIn("Sync-InstalledRuneScapeWrapper", text)
        self.assertIn("Sync-InstalledRuneScapeRuntimeFile", text)
        self.assertNotIn('Sync-InstalledRuneScapeRuntimeFile -SourcePath $installedGameClientExe -ClientDirectory $directory -FileName "rs2client.exe"', text)
        self.assertIn("Win64cOriginalWrapper", text)
        self.assertIn("Win64cPatchedWrapper", text)
        self.assertIn("StagedWrapperPaths", text)


if __name__ == "__main__":
    unittest.main()
